name: eon-llm
channels:
  - conda-forge
  - bioconda
  - defaults
  - apple
  - r
  - pytorch
  - tensorflow
dependencies:
  - anyio=4.3.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fqdn=1.5.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - idna=3.7
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - ipywidgets=8.1.2
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - json5=0.9.25
  - jsonpointer=2.4
  - jsonschema=4.22.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.22.0
  - jupyter=1.0.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.1
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.1.8
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.1
  - jupyterlab_widgets=3.0.10
  - krb5=1.21.2
  - libcxx=16.0.6
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libzlib=1.2.13
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - notebook=7.1.3
  - notebook-shim=0.2.4
  - openssl=3.3.0
  - overrides=7.7.0
  - packaging=24.0
  - pandoc=3.1.13
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.1
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.22
  - pygments=2.17.2
  - pyobjc-core=10.2
  - pyobjc-framework-cocoa=10.2
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python_abi=3.10
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.0.2
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.35.1
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.0
  - send2trash=1.8.3
  - setuptools=69.5.1
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.2
  - terminado=0.18.1
  - tinycss2=1.3.0
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.4
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_utils=0.1.0
  - uri-template=1.3.0
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - contourpy==1.2.1
      - cycler==0.12.1
      - datasets==2.19.1
      - dill==0.3.8
      - filelock==3.14.0
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - huggingface-hub==0.23.2
      - kiwisolver==1.4.5
      - matplotlib==3.9.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.3
      - numpy==1.26.4
      - pandas==2.2.2
      - pillow==10.3.0
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pyparsing==3.1.2
      - regex==2024.5.15
      - safetensors==0.4.3
      - seaborn==0.13.2
      - sympy==1.12.1
      - tokenizers==0.19.1
      - torch==2.2.2
      - tqdm==4.66.4
      - transformers==4.41.2
      - tzdata==2024.1
      - xxhash==3.4.1
      - yarl==1.9.4